export type TChannel = {
  CURRENCY: {
    docIdMajor: string;
    docIdRiskProfile: string;
    docIdSubstandard: string;
    COVERAGE_BUNDLE: string;
    code: string;
    FUND: string[];
    docIdRi: string;
    COVERAGE: {
      coverageObsolete: boolean;
      riderSequence: string;
      groupSequence: string;
      lifeAssureCd: string;
      showAlter: boolean;
      showNb: boolean;
      coverageCd: string;
      coverageBundle: boolean;
      autoSelected?: boolean;
    }[];
    docIdKesehatanAlter: string;
    adminFee: string;
    docIdPrubooster: string;
    docIdStandardGIO: string;
    docIdSpaj: string;
    fundGroupCd: string;
    docIdSpajt: string;
    docIdSpajSio: string;
    docIdStandard: string;
    docIdCutiPremi: string;
    docIdPemulihan: string;
  };
  code: string;
  PAYMENT_FREQUENCY: string[];
  fundGroupCode: string;
  shortName: string;
  lifeAsiaCode: string;
  longName: string;
  status: string;
  productCategory: string;
};

export const CHANNEL: { [key: string]: TChannel } = {
  U13: {
    CURRENCY: {
      docIdMajor: '',
      docIdRiskProfile: '17060334',
      docIdSubstandard: '17040864',
      COVERAGE_BUNDLE: '',
      code: 'IDR',
      FUND: ['PSCF2', 'PSMF2', 'PSIE2', 'PSCB2', 'PSEF2'],
      docIdRi: '17060307',
      COVERAGE: [
        {
          coverageObsolete: false,
          riderSequence: '1',
          groupSequence: '-',
          lifeAssureCd: '01',
          showAlter: true,
          showNb: true,
          coverageCd: 'U13R',
          coverageBundle: false,
        },
        {
          coverageObsolete: false,
          riderSequence: '2',
          groupSequence: '-',
          lifeAssureCd: '01',
          showAlter: true,
          showNb: true,
          coverageCd: 'U1I3',
          coverageBundle: false,
        },
        {
          coverageObsolete: false,
          riderSequence: '2',
          groupSequence: '-',
          lifeAssureCd: '01',
          showAlter: true,
          showNb: true,
          coverageCd: 'H165',
          coverageBundle: false,
        },
      ],
      docIdKesehatanAlter: '',
      adminFee: 'FRMLADMINFEE04',
      docIdPrubooster: '',
      docIdStandardGIO: '',
      docIdSpaj: '17010758',
      fundGroupCd: 'PSGB2',
      docIdSpajt: '',
      docIdSpajSio: '',
      docIdStandard: '17040863',
      docIdCutiPremi: '',
      docIdPemulihan: '',
    },
    code: 'U13',
    PAYMENT_FREQUENCY: ['01', '02', '04', '12'],
    fundGroupCode: '',
    shortName: 'PRULink NextGen Syariah',
    lifeAsiaCode: 'U13',
    longName: 'PRULink NextGen Syariah',
    status: 'ACTIVE',
    productCategory: 'UL',
  },
  U12: {
    CURRENCY: {
      docIdMajor: '',
      docIdRiskProfile: '17060334',
      docIdSubstandard: '17040862',
      COVERAGE_BUNDLE: '',
      code: 'IDR',
      FUND: ['PRFF2', 'PRCF2', 'PRDP2', 'PRMF2', 'PRMP2', 'PREP2', 'PRIE2', 'PRVE2', 'PREF2'],
      docIdRi: '17060307',
      COVERAGE: [
        {
          coverageObsolete: false,
          riderSequence: '2',
          groupSequence: '-',
          lifeAssureCd: '01',
          showAlter: true,
          showNb: true,
          coverageCd: 'U1C5',
          coverageBundle: false,
        },
        {
          coverageObsolete: false,
          riderSequence: '1',
          groupSequence: '-',
          lifeAssureCd: '01',
          showAlter: true,
          showNb: true,
          coverageCd: 'U12R',
          coverageBundle: false,
        },
        {
          coverageObsolete: false,
          riderSequence: '2',
          groupSequence: '-',
          lifeAssureCd: '01',
          showAlter: true,
          showNb: true,
          coverageCd: 'H161',
          coverageBundle: false,
        },
      ],
      docIdKesehatanAlter: '',
      adminFee: 'FRMLADMINFEE02',
      docIdPrubooster: '',
      docIdStandardGIO: '',
      docIdSpaj: '17010757',
      fundGroupCd: 'PGB2',
      docIdSpajt: '',
      docIdSpajSio: '',
      docIdStandard: '17040861',
      docIdCutiPremi: '',
      docIdPemulihan: '',
    },
    code: 'U12',
    PAYMENT_FREQUENCY: ['01', '02', '04', '12'],
    fundGroupCode: '',
    shortName: 'PRULink NextGen',
    lifeAsiaCode: 'U12',
    longName: 'PRULink NextGen',
    status: 'ACTIVE',
    productCategory: 'UL',
  },
  H14: {
    CURRENCY: {
      docIdMajor: '',
      docIdRiskProfile: '17060334',
      docIdSubstandard: '17040894',
      COVERAGE_BUNDLE: '',
      code: 'IDR',
      FUND: ['PRFF', 'PRGC', 'PRIE', 'PREF', 'PREP', 'PRCF', 'PRMP', 'PRMF', 'PRVE', 'PRMF2', 'PRVE2'],
      docIdRi: '17060307',
      COVERAGE: [
        {
          coverageObsolete: false,
          riderSequence: '1',
          groupSequence: '-',
          lifeAssureCd: '01',
          showAlter: false,
          showNb: false,
          coverageCd: 'H141',
          coverageBundle: false,
        },
      ],
      docIdKesehatanAlter: '',
      adminFee: '0',
      docIdPrubooster: '',
      docIdStandardGIO: '',
      docIdSpaj: '17010792',
      fundGroupCd: 'PRDP',
      docIdSpajt: '',
      docIdSpajSio: '',
      docIdStandard: '17040893',
      docIdCutiPremi: '',
      docIdPemulihan: '',
    },
    code: 'H14',
    PAYMENT_FREQUENCY: ['01', '02', '04', '12'],
    fundGroupCode: '',
    shortName: 'PRUWell Medical',
    lifeAsiaCode: 'H14',
    longName: 'PRUWell Medical',
    status: 'ACTIVE',
    productCategory: 'TRD',
  },
  H15: {
    CURRENCY: {
      docIdMajor: '',
      docIdRiskProfile: '17060334',
      docIdSubstandard: '17040896',
      COVERAGE_BUNDLE: '',
      code: 'IDR',
      FUND: ['PSCB', 'PSMF', 'PSIE'],
      docIdRi: '17060307',
      COVERAGE: [
        {
          coverageObsolete: false,
          riderSequence: '1',
          groupSequence: '-',
          lifeAssureCd: '01',
          showAlter: false,
          showNb: false,
          coverageCd: 'H151',
          coverageBundle: false,
        },
      ],
      docIdKesehatanAlter: '',
      adminFee: '0',
      docIdPrubooster: '',
      docIdStandardGIO: '',
      docIdSpaj: '17010791',
      fundGroupCd: 'PRSF',
      docIdSpajt: '',
      docIdSpajSio: '',
      docIdStandard: '17040895',
      docIdCutiPremi: '',
      docIdPemulihan: '',
    },
    code: 'H15',
    PAYMENT_FREQUENCY: ['01', '02', '04', '12'],
    fundGroupCode: '',
    shortName: 'PRUWell Medical Syariah',
    lifeAsiaCode: 'H15',
    longName: 'PRUWell Medical Syariah',
    status: 'ACTIVE',
    productCategory: 'TRD',
  },
  L1Q: {
    CURRENCY: {
      docIdMajor: '',
      docIdRiskProfile: '17060334',
      docIdSubstandard: '17040886',
      COVERAGE_BUNDLE: '',
      code: 'IDR',
      FUND: ['PRCF', 'PRFF', 'PRGC', 'PRIE', 'PREF', 'PREP', 'PRMP', 'PRMF', 'PRVE', 'PRMF2', 'PRVE2'],
      docIdRi: '17060307',
      COVERAGE: [
        {
          coverageObsolete: false,
          riderSequence: '1',
          groupSequence: '-',
          lifeAssureCd: '01',
          showAlter: false,
          showNb: false,
          coverageCd: 'L1QR',
          coverageBundle: false,
        },
      ],
      docIdKesehatanAlter: '',
      adminFee: '0',
      docIdPrubooster: '',
      docIdStandardGIO: '',
      docIdSpaj: '17010773',
      fundGroupCd: 'PRDP',
      docIdSpajt: '',
      docIdSpajSio: '',
      docIdStandard: '17040885',
      docIdCutiPremi: '',
      docIdPemulihan: '',
    },
    code: 'L1Q',
    PAYMENT_FREQUENCY: ['01', '02', '04', '12'],
    fundGroupCode: '',
    shortName: 'PRUAnugerah Syariah',
    lifeAsiaCode: 'L1Q',
    longName: 'PRUAnugerah Syariah',
    status: 'ACTIVE',
    productCategory: 'TRD',
  },
  E1O: {
    CURRENCY: {
      docIdMajor: '',
      docIdRiskProfile: '17060334',
      docIdSubstandard: '17040836',
      COVERAGE_BUNDLE: '',
      code: 'IDR',
      FUND: ['PRCF', 'PRFF', 'PRGC', 'PRIE', 'PREF', 'PREP', 'PRMP', 'PRMF', 'PRVE', 'PRMF2', 'PRVE2'],
      docIdRi: '17060309',
      COVERAGE: [
        {
          coverageObsolete: false,
          riderSequence: '1',
          groupSequence: '-',
          lifeAssureCd: '01',
          showAlter: false,
          showNb: false,
          coverageCd: 'E1O1',
          coverageBundle: false,
        },
        {
          coverageObsolete: false,
          riderSequence: '2',
          groupSequence: '-',
          lifeAssureCd: '02',
          showAlter: false,
          showNb: false,
          coverageCd: 'W123',
          coverageBundle: false,
          autoSelected: true,
        },
      ],
      docIdKesehatanAlter: '',
      adminFee: '0',
      docIdPrubooster: '',
      docIdStandardGIO: '',
      docIdSpaj: '17010623',
      fundGroupCd: 'PRDP',
      docIdSpajt: '',
      docIdSpajSio: '',
      docIdStandard: '17040835',
      docIdCutiPremi: '',
      docIdPemulihan: '',
    },
    code: 'E1O',
    PAYMENT_FREQUENCY: ['01', '02', '04', '12'],
    fundGroupCode: '',
    shortName: 'PRUCerah',
    lifeAsiaCode: 'E1O',
    longName: 'PRUCerah',
    status: 'ACTIVE',
    productCategory: 'TRD',
  },
  E1OP: {
    CURRENCY: {
      docIdMajor: '',
      docIdRiskProfile: '17060334',
      docIdSubstandard: '17040838',
      COVERAGE_BUNDLE: '',
      code: 'IDR',
      FUND: ['PRCF', 'PRFF', 'PRGC', 'PRIE', 'PREF', 'PREP', 'PRMP', 'PRMF', 'PRVE', 'PRMF2', 'PRVE2'],
      docIdRi: '17060309',
      COVERAGE: [
        {
          coverageObsolete: false,
          riderSequence: '1',
          groupSequence: '-',
          lifeAssureCd: '01',
          showAlter: false,
          showNb: false,
          coverageCd: 'E1OR',
          coverageBundle: false,
        },
        {
          coverageObsolete: false,
          riderSequence: '2',
          groupSequence: '-',
          lifeAssureCd: '02',
          showAlter: false,
          showNb: false,
          coverageCd: 'W121',
          coverageBundle: false,
          autoSelected: true,
        },
      ],
      docIdKesehatanAlter: '',
      adminFee: '0',
      docIdPrubooster: '',
      docIdStandardGIO: '',
      docIdSpaj: '17010624',
      fundGroupCd: 'PRDP',
      docIdSpajt: '',
      docIdSpajSio: '',
      docIdStandard: '17040837',
      docIdCutiPremi: '',
      docIdPemulihan: '',
    },
    code: 'E1OP',
    PAYMENT_FREQUENCY: ['01', '02', '04', '12'],
    fundGroupCode: '',
    shortName: 'PRUCerah Plus',
    lifeAsiaCode: 'E1O',
    longName: 'PRUCerah Plus',
    status: 'ACTIVE',
    productCategory: 'TRD',
  },
  C16: {
    CURRENCY: {
      docIdMajor: '',
      docIdRiskProfile: '17060334',
      docIdSubstandard: '17040844',
      COVERAGE_BUNDLE: '',
      code: 'IDR',
      FUND: ['PRCF', 'PRFF', 'PRGC', 'PRIE', 'PREF', 'PREP', 'PRMP', 'PRMF', 'PRVE', 'PRMF2', 'PRVE2'],
      docIdRi: '17060307',
      COVERAGE: [
        {
          coverageObsolete: false,
          riderSequence: '1',
          groupSequence: '-',
          lifeAssureCd: '01',
          showAlter: false,
          showNb: false,
          coverageCd: 'C16R',
          coverageBundle: false,
        },
      ],
      docIdKesehatanAlter: '',
      adminFee: '0',
      docIdPrubooster: '',
      docIdStandardGIO: '17040843',
      docIdSpaj: '17010660',
      fundGroupCd: 'PRDP',
      docIdSpajt: '',
      docIdSpajSio: '',
      docIdStandard: '17040843',
      docIdCutiPremi: '',
      docIdPemulihan: '',
    },
    code: 'C16',
    PAYMENT_FREQUENCY: ['01', '02', '04', '12'],
    fundGroupCode: '',
    shortName: 'PRUSolusi Kondisi Kritis Syariah',
    lifeAsiaCode: 'C16',
    longName: 'PRUSolusi Kondisi Kritis Syariah',
    status: 'ACTIVE',
    productCategory: 'TRD',
  },
  T1Q: {
    CURRENCY: {
      docIdMajor: '',
      docIdRiskProfile: '17060334',
      docIdSubstandard: '17040525',
      COVERAGE_BUNDLE: '',
      code: 'IDR',
      FUND: ['PRCF', 'PRFF', 'PRGC', 'PRIE', 'PREF', 'PREP', 'PRMP', 'PRMF', 'PRVE', 'PRMF2', 'PRVE2'],
      docIdRi: '17060307',
      COVERAGE: [
        {
          coverageObsolete: false,
          riderSequence: '1',
          groupSequence: '-',
          lifeAssureCd: '01',
          showAlter: true,
          showNb: true,
          coverageCd: 'T1QR',
          coverageBundle: false,
        },
      ],
      docIdKesehatanAlter: '',
      adminFee: '0',
      docIdPrubooster: '',
      docIdStandardGIO: '',
      docIdSpaj: '17010465',
      fundGroupCd: 'PRDP',
      docIdSpajt: '',
      docIdSpajSio: '',
      docIdStandard: '17040521',
      docIdCutiPremi: '',
      docIdPemulihan: '',
    },
    code: 'T1Q',
    PAYMENT_FREQUENCY: ['01', '02', '04', '12'],
    fundGroupCode: '',
    shortName: 'PRUCritical Benefit 88 (Premi Berkala)',
    lifeAsiaCode: 'T1Q',
    longName: 'PRUCritical Benefit 88 (Premi Berkala)',
    status: 'ACTIVE',
    productCategory: 'TRD',
  },
  T1P: {
    CURRENCY: {
      docIdMajor: '',
      docIdRiskProfile: '17060334',
      docIdSubstandard: '17040523',
      COVERAGE_BUNDLE: '',
      code: 'IDR',
      FUND: ['PRCF', 'PRFF', 'PRGC', 'PRIE', 'PREF', 'PREP', 'PRMP', 'PRMF', 'PRVE', 'PRMF2', 'PRVE2'],
      docIdRi: '17060307',
      COVERAGE: [
        {
          coverageObsolete: false,
          riderSequence: '1',
          groupSequence: '-',
          lifeAssureCd: '01',
          showAlter: true,
          showNb: true,
          coverageCd: 'T1PR',
          coverageBundle: false,
        },
      ],
      docIdKesehatanAlter: '',
      adminFee: '0',
      docIdPrubooster: '',
      docIdStandardGIO: '',
      docIdSpaj: '17010465',
      fundGroupCd: 'PRDP',
      docIdSpajt: '',
      docIdSpajSio: '',
      docIdStandard: '17040519',
      docIdCutiPremi: '',
      docIdPemulihan: '',
    },
    code: 'T1P',
    PAYMENT_FREQUENCY: ['00'],
    fundGroupCode: '',
    shortName: 'PRUCritical Benefit 88 (Premi Tunggal)',
    lifeAsiaCode: 'T1P',
    longName: 'PRUCritical Benefit 88 (Premi Tunggal)',
    status: 'ACTIVE',
    productCategory: 'TRD',
  },
  L1WR: {
    CURRENCY: {
      docIdMajor: '',
      docIdRiskProfile: '17060334',
      docIdSubstandard: '17040892',
      COVERAGE_BUNDLE: '',
      code: 'IDR',
      FUND: ['PRCF', 'PRFF', 'PRGC', 'PRIE', 'PREF', 'PREP', 'PRMP', 'PRMF', 'PRVE', 'PRMF2', 'PRVE2'],
      docIdRi: '17060307',
      COVERAGE: [
        {
          coverageObsolete: false,
          riderSequence: '-',
          groupSequence: '-',
          lifeAssureCd: '01',
          showAlter: false,
          showNb: false,
          coverageCd: 'L1WR',
          coverageBundle: false,
        },
      ],
      docIdKesehatanAlter: '',
      adminFee: '0',
      docIdPrubooster: '',
      docIdStandardGIO: '',
      docIdSpaj: '17010790',
      fundGroupCd: 'PRDP',
      docIdSpajt: '',
      docIdSpajSio: '',
      docIdStandard: '17040891',
      docIdCutiPremi: '',
      docIdPemulihan: '',
    },

    code: 'L1W',
    PAYMENT_FREQUENCY: ['01', '02', '04', '12'],
    fundGroupCode: '',
    shortName: 'PRUFuture',
    lifeAsiaCode: 'L1W',
    longName: 'PRUFuture',
    status: 'ACTIVE',
    productCategory: 'TRD',
  },
  L1WD: {
    CURRENCY: {
      docIdMajor: '',
      docIdRiskProfile: '17060334',
      docIdSubstandard: '17040892',
      COVERAGE_BUNDLE: '',
      code: 'USD',
      FUND: [],
      docIdRi: '17060307',
      COVERAGE: [
        {
          coverageObsolete: false,
          riderSequence: '-',
          groupSequence: '-',
          lifeAssureCd: '01',
          showAlter: false,
          showNb: false,
          coverageCd: 'L1WD',
          coverageBundle: false,
        },
      ],
      docIdKesehatanAlter: '',
      adminFee: '0',
      docIdPrubooster: '',
      docIdStandardGIO: '',
      docIdSpaj: '17010790',
      fundGroupCd: 'PRDP',
      docIdSpajt: '',
      docIdSpajSio: '',
      docIdStandard: '17040891',
      docIdCutiPremi: '',
      docIdPemulihan: '',
    },
    code: 'L1W',
    PAYMENT_FREQUENCY: ['01', '02', '04', '12'],
    fundGroupCode: '',
    shortName: 'PRUFuture',
    lifeAsiaCode: 'L1W',
    longName: 'PRUFuture',
    status: 'ACTIVE',
    productCategory: 'TRD',
  },
  U17R: {
    CURRENCY: {
      docIdMajor: '',
      docIdRiskProfile: '17060334',
      docIdSubstandard: '17040874',
      COVERAGE_BUNDLE: '',
      code: 'IDR',
      FUND: ['PRFF2', 'PRCF2', 'PRDP2', 'PRMF2', 'PRMP2', 'PREP2', 'PRIE2', 'PRVE2'],
      docIdRi: '17060307',
      COVERAGE: [
        {
          coverageObsolete: false,
          riderSequence: '',
          groupSequence: '-',
          lifeAssureCd: '01',
          showAlter: true,
          showNb: true,
          coverageCd: 'U17R',
          coverageBundle: false,
        },
      ],
      docIdKesehatanAlter: '',
      adminFee: '5000',
      docIdPrubooster: '',
      docIdStandardGIO: '',
      docIdSpaj: '17010767',
      fundGroupCd: 'PRIA2',
      docIdSpajt: '',
      docIdSpajSio: '',
      docIdStandard: '17040873',
      docIdCutiPremi: '',
      docIdPemulihan: '',
    },
    code: 'U17R',
    PAYMENT_FREQUENCY: ['00'],
    fundGroupCode: '',
    shortName: 'PRULink Investor Account',
    lifeAsiaCode: 'U17',
    longName: 'PRULink Investor Account',
    status: 'ACTIVE',
    productCategory: 'UL',
  },
  U17D: {
    CURRENCY: {
      docIdMajor: '',
      docIdRiskProfile: '17060334',
      docIdSubstandard: '17040874',
      COVERAGE_BUNDLE: '',
      code: 'USD',
      FUND: ['PDFF2', 'PDGV2', 'PDGC2', 'PDGM2'],
      docIdRi: '17060307',
      COVERAGE: [
        {
          coverageObsolete: false,
          riderSequence: '',
          groupSequence: '-',
          lifeAssureCd: '01',
          showAlter: true,
          showNb: true,
          coverageCd: 'U17D',
          coverageBundle: false,
        },
      ],
      docIdKesehatanAlter: '',
      adminFee: '0.5',
      docIdPrubooster: '',
      docIdStandardGIO: '',
      docIdSpaj: '17010767',
      fundGroupCd: 'PDIA2',
      docIdSpajt: '',
      docIdSpajSio: '',
      docIdStandard: '17040873',
      docIdCutiPremi: '',
      docIdPemulihan: '',
    },
    code: 'U17D',
    PAYMENT_FREQUENCY: ['00'],
    fundGroupCode: '',
    shortName: 'PRULink Investor Account',
    lifeAsiaCode: 'U17',
    longName: 'PRULink Investor Account',
    status: 'ACTIVE',
    productCategory: 'UL',
  },
};
