export * from './spaj-before-proceeding/spaj-before-proceeding.screen';
export * from './spaj-data-completeness/spaj-data-completeness.screen';
export * from './spaj-policy-owner-data/spaj-policy-owner-data.screen';
export * from './spaj-primary-insured-candidate/spaj-primary-insured-candidate.screen';
export * from './spaj-primary-insured-active/spaj-primary-insured-active.screen';
export * from './spaj-additional-insured-active/spaj-additional-insured-active.screen';
export * from './spaj-life-style/spaj-life-style.screen';
export * from './spaj-physical-habits/spaj-physical-habits.screen';
export * from './spaj-family-history/spaj-family-history.screen';
export * from './spaj-medical-history/spaj-medical-history.screen';
export * from './spaj-premium-payer-candidate/spaj-premium-payer-candidate.screen';
export * from './spaj-topup/spaj-topup.screen';
export * from './spaj-topup-premium-payer/spaj-topup-premium-payer.screen';
export * from './spaj-beneficiary-candidate/spaj-beneficiary-candidate.screen';
export * from './spaj-doc-prospective-policyholder/spaj-doc-prospective-policyholder.screen';
export * from './spaj-doc-primary-participant-candidate/spaj-doc-primary-participant-candidate.screen';
export * from './spaj-amandement/spaj-amandement.screen';
export * from './disclaimer/disclaimer';
export * from './link-submitted/link-sumbitted';
export * from './sqs-signature/sqs-signature.screen';
export * from './spaj-doc-premium-payor/spaj-doc-premium-payor.screen';
export * from './spaj-doc-topup-payor/spaj-doc-topup-payor.screen';
export * from './spaj-signature/spaj-signature.screen';
export * from './spaj-payment/spaj-payment.screen'
export * from './form-conversion/form-conversion.screen'
export * from './spaj-digital-sign/spaj-digital-sign.screen'
export * from './spaj-underwriting-decision/spaj-underwriting-decision.screen';
export * from './spaj-exclusion-offering/spaj-exclusion-offering.screen';
export * from './spaj-lsar/spaj-lsar.screen';
export * from './spaj-abr/spaj-abr.screen';
